export const UPDATE_CONTACTS = "UPDATE_CONTACTS";
export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const TOGGLE_LIKE_CONTACT = "TOGGLE_LIKE_CONTACT";
